services:
  - name: database-backup-job
    type: cron
    schedule: "0 3 * * *"
    region: oregon
    env: docker
    plan: standard
    dockerfilePath: ./Dockerfile
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: BUCKET_NAME
        sync: false
      - key: BUCKET_PREFIX
        sync: false
      - key: GCP_CREDENTIALS
        sync: false
      # Postgres version of your Postgres instance
      # For example, 14
      - key: POSTGRES_VERSION
        sync: false

